**/:
  ros__parameters:
    target_frame: ""
    transform_tolerance: 0.01
    queue_size: 0
    min_height: 0.0 
    max_height: 1.0
    # -$M_PI / 2)
    angle_min: -1.5707963267948966
    # $_MPI / 2
    angle_max: 1.5707963267948966
    # $M_PI / 360
    angle_increment: 0.008726646259971648
    scan_time: 0.03333333333333333
    range_min: 0.45
    range_max: 4.0
    inf_epsilon: 1.0
    use_inf: true
